config/routes.rb
PrototypeRobotics::Application.routes.draw do
  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  root :to => 'home#index'
  mount Forem::Engine, :at => '/forums'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get "dashboard" => "dashboard#index"
  get "alerts" => "dashboard#alerts"
  post "change_user_password" => "passwords#change_password"
  resources :projects
  resources :tutorials
  resources :steps
  resources :articles, :path => "blog"
  resources :galleries
  resources :images do
    get "remove" => "images#remove"
  end

  match "/admin" => "admin/dashboard#index"
  namespace :admin do
    resources :users
    resources :projects
    post "approve_project" => "projects#approve"
    resources :tutorials
    resources :steps
    resources :articles
    resources :galleries
    get "read_notice"       => "dashboard#read_notice"
    get "read_all_notices"  => "dashboard#read_all_notices"
  end

  match "search_projects" => "projects#search_projects"
  match "search" => "home#search"

  get "about_me" => "home#about_me"
  get "links" => "home#links"

end

app/views/shared/_content_slider.html.haml
.carousel-inner
  - content.each do |c|
    .item
      %center
        = link_to image_tag(c.image.url(:large)), c
      .carousel-caption
        %h4= c.name if c.name.present?
        %p
          =h truncate(c.description, :length => 100 ).html_safe

%a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} ‹
%a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} ›

:javascript
  $(document).ready(function(){
    $('.carousel').carousel()
  });

app/views/shared/_disqus.html.haml
#disqus_thread
:javascript
  var disqus_shortname = 'prototyperobotics'; // put the short name you signed up with here
  var disqus_developer = #{ Rails.env == "production" ? '0' : '1' };
  var disqus_title = "#{ title }";
  var disqus_url = "#{ request.url }";
  var disqus_identifier = "#{ request.fullpath }";
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();

app/views/shared/_forem_menu.html.haml
.navbar
  .navbar-inner
    .container
      %ul.nav
        - unless current_user && current_user.forem_admin
          %li= link_to "Home", main_app.root_path
          %li= link_to "About me", '/about_me'
          %li= link_to "Links", '/links'
        %li= link_to "Blog", main_app.articles_path
        %li= link_to "Projects", main_app.projects_path
        %li= link_to "Tutorials", main_app.tutorials_path
        %li= link_to "Forums", "/forums"
        - if current_user && current_user.forem_admin
          %li= link_to "Moderate", admin_forums_path

      %ul.nav.pull-right
        - if current_user
          %li= link_to "Welcome #{current_user.username}", '#'
          %li= link_to('Logout', main_app.destroy_user_session_path, :method => :delete)
        - else
          %li= link_to "Login", main_app.new_user_session_path
          %li= link_to "Register", main_app.new_user_registration_path

app/views/shared/_google_ad_show.html.erb
<script type="text/javascript"><!--
  google_ad_client = "ca-pub-5968396000453618";
  /* show2 */
  google_ad_slot = "0560959053";
  google_ad_width = 728;
  google_ad_height = 90;
  //-->
</script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/shared/_menu.html.haml
.navbar
  .navbar-inner
    .container
      %ul.nav
        %li.visible-desktop= link_to "Home", root_path
        %li.visible-desktop= link_to "About me", '/about_me'
        %li.visible-desktop= link_to "Links", '/links'
        %li= link_to "Blog", articles_path
        %li= link_to "Projects", projects_path
        %li= link_to "Tutorials", tutorials_path
        %li= link_to "Forums", "/forums"
        - if current_user
          %li= link_to "Dashboard", dashboard_path
          - if current_user.forem_admin
            %li= link_to "Admin", admin_path
          %li= link_to('Logout', destroy_user_session_path, :method => :delete)
        - else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Register", new_user_registration_path

app/views/shared/_nivo_slider.html.haml
.slider-wrapper.theme-default#featured
  #slider.nivoSlider
    - content.each do |c|
      = link_to image_tag(c.image.url(:large), :title => c.name), c


:javascript
  $(document).ready(function(){
    $('#slider').nivoSlider({
      pauseTime: 5000
    });
  });

app/views/shared/_registration.html.erb
<p>
  <%= f.label :username, t(:username) %><br />
  <%= f.text_field :username, :class => 'title' %>
</p>

app/views/shared/_user_form.html.erb
<%= f.field_container :username do %>
  <%= f.label :username, t(:username) %><br />
  <%= f.text_field :username %>
  <%= f.error_message_on :username %>
<% end %>

<%= f.field_container :active do %>
  <%= f.label :active, t(:active) %><br />
  <%= f.check_box :active %>
  <%= f.error_message_on :active %>
<% end %>

app/views/shared/_user_projects.html.haml
%h3
  My Projects
  .pull-right= link_to "New Project", main_app.new_project_path(:id => @user.id)

%hr

.row
  .span12
    - if @user.projects
      - @user.projects.each do |project|
        .span4
          %h4= project.name
          .project_image= link_to image_tag(project.image.url(:thumb), :class => "imgshadow"), main_app.project_path(project)
          =h truncate(project.description.html_safe, :length => 100 )
          .space= link_to "edit project", main_app.edit_project_path(project)
    %p