config/routes.rb
PrototypeRobotics::Application.routes.draw do
  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  root :to => 'home#index'
  mount Forem::Engine, :at => '/forums'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get "dashboard" => "dashboard#index"
  get "alerts" => "dashboard#alerts"
  post "change_user_password" => "passwords#change_password"
  resources :projects
  resources :tutorials
  resources :steps
  resources :articles, :path => "blog"
  resources :galleries
  resources :images do
    get "remove" => "images#remove"
  end

  match "/admin" => "admin/dashboard#index"
  namespace :admin do
    resources :users
    resources :projects
    post "approve_project" => "projects#approve"
    resources :tutorials
    resources :steps
    resources :articles
    resources :galleries
    get "read_notice"       => "dashboard#read_notice"
    get "read_all_notices"  => "dashboard#read_all_notices"
  end

  match "search_projects" => "projects#search_projects"
  match "search" => "home#search"

  get "about_me" => "home#about_me"
  get "links" => "home#links"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :add_vars, :only => [:index]
  layout 'application'

  def about_me
  end

  def links
  end

  def index
  end

  def add_vars
    @featured_content = Article.published.featured
    @featured_projects = Project.active.published.featured
    if !@featured_projects.empty?
      @featured_projects.each do |project|
        @featured_content.push(project)
      end
    end
    @featured_content = @featured_content.sort{|x,y| y.created_at <=> x.created_at }
    @articles = Article.published.order("created_at ASC").last(3).reverse
    @projects = Project.active.published.order("created_at ASC").last(3).reverse
    @tutorials = Tutorial.order("created_at ASC").all.last(3).reverse
  end

  def search
    if params["search"]
      @search = params["search"]
      @search_results = PgSearch.multisearch(@search)

      @results = []
      @search_results.select{|p| p.searchable_type == "Project"}.each do |project|
        p = Project.find(project.searchable_id)
        @results.push(p) if p.active?
      end

      @search_results.select{|p| p.searchable_type == "Article"}.each do |article|
        a = Article.find(article.searchable_id)
        @results.push(a) if a.active?
      end

      @search_results.select{|p| p.searchable_type == "Tutorial"}.each do |tutorial|
        @results.push(Tutorial.find(tutorial.searchable_id))
      end
      render 'home/search'
    else
      redirect_to '/'
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_me.html.haml
.row-fluid
  %h2
    .title My name is JD Warren and I build things.
.row-fluid
  .heading
    %p
    I have taken apart nearly everything I have ever owned - to me it is more important to know how it works, than to actually have it work.
    %p
    Lately, I have transitioned from hardware hacking into the far more meticulous world of software. I work as a Ruby on Rails developer, building web applications at Isotope11. When i'm not at work coding or at home with my lovely wife, i'm probably in the garage hacking on something or writing about somthing i've just hacked.
    %p
    %h3 Here are a few publications that I have been in:
    %p
    = link_to "MAKE Magazine 22", "http://www.make-digital.com/make/vol22#pg1"
    %br
    = link_to "UAB alumni magazine", "http://www.uab.edu/uabmagazine/fall2010/departments/alumni"
    %br
    = link_to "Wired Magazine - 21 Awesome Hacks (#18)", "http://www.wired.com/magazine/2011/03/ff_makestuff_projects/"
    %br
    = link_to "Arduino Robotics (my new book)", "http://www.amazon.com/Arduino-Robotics-John-David-Warren/dp/1430231831"
    %p
    %h3 And a few videos:
    %p
    = link_to "MAKE: Latest in Arduino (02)", "http://blog.makezine.com/archive/2011/07/the-latest-in-arduino-episode-2.html"
    %br
    = link_to "MAKE: Latest in Arduino (03)", "http://www.youtube.com/watch?v=uhDou04jj7Q"
    %p

app/views/home/index.html.haml
.row-fluid
  %center
    %h1
      .title Welcome to Prototype Robotics
    %i
      the new home of
      = link_to "Rediculouslygoodlooking.com", 'http://rediculous.prototyperobotics.com'
  .heading
    .row-fluid
      .span1.book
        = link_to image_tag("book.jpg", :class => "imgshadow"), "http://prototyperobotics.com/blog/arduino-robotics"
      .span11
        %p
          If you are here to find out more about my book "Arduino Robotics",
          = link_to "click here", "http://prototyperobotics.com/blog/arduino-robotics"
          or you can check it out on Amazon:
          = link_to "Arduino Robotics.", "http://www.amazon.com/Arduino-Robotics-John-David-Warren/dp/1430231831"
        %p
          This site exists to help anyone who needs help, so if you would like to post a question or comment or need help with a specific project, please do so on the new
          = link_to "Forums.", forem.forums_path
          = " - I will personally answer your posts as soon as I get a chance."
        %p
          For those who have built a project from my book, please consider sharing it on my site. Once you register, you can go to
          = link_to "your Dashboard", dashboard_path
          and create a new project. You can add a description of your project and some images to show off your work.


.visible-desktop
  .row-fluid
    .span7
      %h2 Featured Content
      = render 'shared/nivo_slider', :content => @featured_content
    .span5
      %h2.inline Recent Articles
      %h5.inline= link_to "view all articles", articles_path
      - @articles.each do |article|
        .well
          .article
            .article_image= link_to image_tag(article.image.url(:thumb), :class => "imgshadow"), article_path(article)
            %h3= article.name
            %h5
              - if article.user
                = "posted by: #{article.user.username}"
              - else
                n/a
            %h5= article.created_at.strftime("Date: %m/%d/%Y")
.hidden-desktop
  .row-fluid
    .span12
      %h2.inline Recent Articles
      %h5.inline= link_to "view all articles", articles_path
      - @articles.each do |article|
        .well
          .article
            .article_image= link_to image_tag(article.image.url(:thumb), :class => "imgshadow"), article_path(article)
            %h3= article.name
            %h5
              - if article.user
                = "posted by: #{article.user.username}"
              - else
                n/a
            %h5= article.created_at.strftime("Date: %m/%d/%Y")

%hr
.row-fluid
  .span6
    %h2.inline Recent Projects
    %h5.inline= link_to "view all projects", projects_path
    - @projects.each do |project|
      .well
        .row-fluid
          .span3.pad
            = link_to image_tag(project.image.url(:thumb), :class => "imgshadow"), project_path(project)
          .span9
            %h4= link_to project.name, project_path(project)
            =h truncate(project.description, :length => 100 ).html_safe
  .span6
    %h2.inline Recent Tutorials
    %h5.inline= link_to "view all tutorials", tutorials_path
    - @tutorials.each do |tutorial|
      .well
        .row-fluid
          .span3.pad
            = link_to image_tag(tutorial.image.url(:thumb), :class => "imgshadow"), tutorial_path(tutorial)
          .span9
            %h4= link_to tutorial.name, tutorial_path(tutorial)
            =h truncate(tutorial.description, :length => 100 ).html_safe

app/views/home/links.html.haml
.links
  .inline
    %h3 My Links
    %ul
      %li
        %a{:href => "http://www.instructables.com/member/johndavid400/"} My Instructables
      %li
        %a{:href => "https://github.com/johndavid400"} My Github
      %li
        %a{:href => "http://www.youtube.com/user/johndavid400"} My Youtube channel
      %li
        %a{:href => "http://rediculous.prototyperobotics.com/"} My old website
  .inline
    %h3 Favorite Links
    %ul
      %li
        %a{:href => "http://hackaday.com/"} Hackaday
      %li
        %a{:href => "http://blog.makezine.com/home-page-include/"} MAKE
      %li
        %a{:href => "http://www.instructables.com/"} Instructables
      %li
        %a{:href => "http://arduino.cc"} Arduino
  .inline
    %h3 Helpful
    %ul
      %li
        %a{:href => "http://www.sparkfun.com"} Sparkfun
      %li
        %a{:href => "http://www.adafruit.com/tutorials"} LadyAda
      %li
        %a{:href => "http://www.dannyg.com/examples/res2/resistor.htm"} Resistor Colors
      %li
        %a{:href => "http://www.willingtons.com/mymac/ohm_calc.htm"} Ohm Calculator
  .inline
    %h3 Suppliers
    %ul
      %li
        %a{:href => "http://www.digikey.com/"} Digikey
      %li
        %a{:href => "http://www.radioshack.com/home/index.jsp"} Radio Shack
      %li
        %a{:href => "http://www.seeedstudio.com/depot/"} Seeed Studio
      %li
        %a{:href => "http://www.ebay.com"} Ebay

app/views/home/search.html.haml
.board
  .pad
    %h1= "Search Results for '#{@search}'"

    - if @results.empty?
      %h3 Your search did not return any results.
    - else
      %h3= "Your search returned #{@results.count} results"

    .search_group
      - if !@results.empty?
        %h2 Results
        %ol
          - @results.each do |result|
            %li
              .well
                .row-fluid
                  .span2
                    = link_to image_tag(result.image.url(:thumb), :class => "imgshadow"), result
                  .span10
                    %h4
                      = link_to result.name, result
                      = "(#{result.class.name})"
                    =h truncate(result.description, :length => 250 ).html_safe