config/routes.rb
PrototypeRobotics::Application.routes.draw do
  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  root :to => 'home#index'
  mount Forem::Engine, :at => '/forums'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get "dashboard" => "dashboard#index"
  get "alerts" => "dashboard#alerts"
  post "change_user_password" => "passwords#change_password"
  resources :projects
  resources :tutorials
  resources :steps
  resources :articles, :path => "blog"
  resources :galleries
  resources :images do
    get "remove" => "images#remove"
  end

  match "/admin" => "admin/dashboard#index"
  namespace :admin do
    resources :users
    resources :projects
    post "approve_project" => "projects#approve"
    resources :tutorials
    resources :steps
    resources :articles
    resources :galleries
    get "read_notice"       => "dashboard#read_notice"
    get "read_all_notices"  => "dashboard#read_all_notices"
  end

  match "search_projects" => "projects#search_projects"
  match "search" => "home#search"

  get "about_me" => "home#about_me"
  get "links" => "home#links"

end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :name, :description, :user_id, :image, :image_file_name, :slug, :category

  has_many :steps
  has_many :galleries

  accepts_nested_attributes_for :steps

  has_attached_file :image, :styles => { :large => "640x480>", :medium => "320x240>", :thumb => "100x100>" }

  include PgSearch
  multisearchable :against => [:name, :description]

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/controllers/admin/tutorials_controller.rb
class Admin::TutorialsController < Admin::AdminController

  def index
    @tutorials = Tutorial.all
  end

  def show
    @tutorial = Tutorial.find(params[:id])
  end

  def new
    @tutorial = Tutorial.new()
  end

  def create
    @tutorial = Tutorial.new(params[:tutorial])
    if @tutorial.save
      redirect_to admin_tutorials_path, notice: 'Tutorial was successfully created.'
    end
  end

  def edit
    @tutorial = Tutorial.find(params[:id])
  end

  def update
    @tutorial = Tutorial.find(params[:id])
    @tutorial.update_attributes(params[:tutorial])
    if @tutorial.save
      redirect_to edit_admin_tutorial_path(@tutorial), notice: 'Tutorial was successfully updated.'
    end
  end

  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy
    redirect_to admin_tutorials_path
  end

end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController

  def index
    @tutorials = Tutorial.all
  end

  def show
    @tutorial = Tutorial.find(params[:id])
  end

end

app/views/tutorials/index.html.haml
%h1.title Tutorials List
.listing
  %table.table-striped
    %tr
      %th Image
      %th Name
      %th Number of Steps

    - @tutorials.each do |tutorial|
      %tr
        %td= link_to image_tag(tutorial.image.url(:thumb)), tutorial_path(tutorial)
        %td= link_to tutorial.name, tutorial_path(tutorial)
        %td= tutorial.steps.count

app/views/tutorials/show.html.haml
%h2.title
  = link_to "Tutorials ", tutorials_path
  = "/ #{@tutorial.name}" 
%center
  .google_ad_show= render "shared/google_ad_show"
.listing
  %p#notice= notice

  %center.white_box
    %h3= @tutorial.name
  %center
    = image_tag(@tutorial.image.url(:large), :class => "imgshadow")
  %p
  .clear_steps.white_box
    = @tutorial.description.html_safe
    %p
    %b Category:
    = @tutorial.category


  - if !@tutorial.steps.empty?
    - @tutorial.steps.each do |step|
      .step_box
        %b= step.step_number
        = link_to image_tag(step.image.url(:thumb)), step_path(step)
        = step.name.html_safe

  .clear_steps
%p
= render :partial => "shared/disqus", :locals => { title: @tutorial.name }
%p
  = link_to 'Back', :back