config/routes.rb
PrototypeRobotics::Application.routes.draw do
  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  root :to => 'home#index'
  mount Forem::Engine, :at => '/forums'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get "dashboard" => "dashboard#index"
  get "alerts" => "dashboard#alerts"
  post "change_user_password" => "passwords#change_password"
  resources :projects
  resources :tutorials
  resources :steps
  resources :articles, :path => "blog"
  resources :galleries
  resources :images do
    get "remove" => "images#remove"
  end

  match "/admin" => "admin/dashboard#index"
  namespace :admin do
    resources :users
    resources :projects
    post "approve_project" => "projects#approve"
    resources :tutorials
    resources :steps
    resources :articles
    resources :galleries
    get "read_notice"       => "dashboard#read_notice"
    get "read_all_notices"  => "dashboard#read_all_notices"
  end

  match "search_projects" => "projects#search_projects"
  match "search" => "home#search"

  get "about_me" => "home#about_me"
  get "links" => "home#links"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :description, :user_id, :image, :image_file_name, :slug, :category

  belongs_to :user
  has_many :steps
  has_many :notifications
  has_one :gallery

  scope :published, where(:published => true)
  scope :pending, where(:published => false)
  scope :active, where(:deleted => false)
  scope :featured, where(:featured => true)

  accepts_nested_attributes_for :steps

  has_attached_file :image, :styles => { :large => "640x480>", :medium => "320x240>", :thumb => "100x100>" }

  include PgSearch
  multisearchable :against => [:name, :description]

  extend FriendlyId
  friendly_id :name, use: :slugged

  def active?
    published == true && deleted == false
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      update_admin_attributes
      redirect_to admin_projects_path, notice: 'Project was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      update_admin_attributes
      redirect_to edit_admin_project_path(@project), notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_path
  end

  def approve
    @project = Project.find(params[:id])
    @project.published = true
    @project.save
    redirect_to admin_projects_path
  end

  def update_admin_attributes
    @project.featured = true if params[:project][:featured] == "1"
    @project.published = true if params[:project][:published] == "1"
    @project.save
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :search_projects]

  def index
    @projects = Project.active.published
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    if params[:id].present?
      @user = User.find(params[:id])
      @project = @user.projects.new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = current_user.projects.new(params[:project])
    if @project.save
      @project.notifications.create(message: "#{@project.user.username} just created project #{@project.name}.")
      send_email
      redirect_to dashboard_path, notice: 'Project was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @project = Project.find(params[:id])
    verify_user(@project.user)
    if @project.update_attributes(params[:project])
      @project.notifications.create(message: "#{@project.user.username} just updated project #{@project.name}.")
      redirect_to dashboard_path, notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    verify_user(@project.user)
    @project.deleted = true
    @project.save
    redirect_to dashboard_path, notice: 'Project was successfully deleted.'
  end

  def search_projects
    @projects = Project.published.active.select{|p| p.category == params[:category] }
    render "index"
  end

  def verify_user(user)
    if user == current_user
      return true
    else
      redirect_to root_path, notice: 'You are not allowed to create projects for other users.'
    end
  end

  def send_email
    ProjectNotifier.admin(@project.id).deliver
  rescue
    "The email failed yo"
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.haml
= form_for ([:admin, @project]) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this tutorial from being saved:
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend
      Project
    .clearfix
      = f.label :name
      .input= f.text_field :name
    .clearfix
      = f.label :description
      .input= f.cktext_area :description
    .clearfix
      = f.label :category
      .input= f.text_field :category
    .clearfix
      .inline
        = f.check_box :featured
      .inline
        = f.label :featured
    .clearfix
      .inline
        .input= f.check_box :published
      .inline
        = f.label :published
    - if @project.image
      = image_tag(@project.image.url(:thumb), :class => "imgshadow")
    .clearfix
      = f.label :image
      .input= f.file_field :image

  .actions
    = f.submit :submit, :class => 'btn primary'

%hr

- if @project.id.present?
  .row-fluid
    %h3.pull-left Project Gallery
    .pull-right= link_to "Add Image to Gallery", new_image_path(project: @project.id), :class => "btn"

  - if @project.gallery.present?
    %hr
    .row-fluid
      - @project.gallery.images.each do |image|
        .inline
          %center
            .row
              = link_to image_tag(image.attachment.url(:thumb), :class => "imgshadow"), image.attachment.url
            .row
              = link_to "remove", image_remove_path(image), :confirm => "Are you sure you want to remove this image?"
  %hr

= link_to 'Back', tutorials_path, :class => 'btn'

app/views/admin/projects/edit.html.haml
.board
  %h2= "Editing #{@project.name}"

  = render 'form'

  = link_to 'Back', projects_path

app/views/admin/projects/index.html.haml
.board
  %h1.inline Admin Projects List
  .pull-right= link_to 'New Project', new_admin_project_path, :class => "btn btn-success"

  %table
    %tr
      %th Image
      %th Name
      %th Type
      %th Actions

    - @projects.each do |project|
      %tr
        %td= link_to image_tag(project.image.url(:thumb)), project_path(project)
        %td= link_to project.name, admin_project_path(project)
        %td= project.category
        %td
          = link_to 'Edit', edit_admin_project_path(project), :class => "btn btn-warning"
          = link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger"
          = link_to 'Approve', admin_approve_project_path(id: project), :class => "btn btn-success" unless project.published

  %br

  = link_to 'New Project', new_admin_project_path

app/views/admin/projects/new.html.haml
.board
  %h2 New project

  = render 'form'

  = link_to 'Back', projects_path